import csv
import json
import os
import re
import shutil
import subprocess
import sys
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
START, END = "<a id='numbers-start'></a>", "<a id='numbers-end'></a>"
CHECKS_START, CHECKS_END = "<a id='checks-start'></a>", "<a id='checks-end'></a>"
run = json.loads((ROOT / "out/engine_run.json").read_text())
changes = json.loads((ROOT / "out/changes.json").read_text())
buildings = json.loads((ROOT / "out/buildings.json").read_text())
rules_file = json.loads((ROOT / "out/rules.json").read_text())
rules = rules_file["rules"]

status = {}
for b in buildings.values():
    status[b["city_status"]] = status.get(b["city_status"], 0) + 1
failed = sum(r.get("status") == "failed" for r in rules)
rc = run["result_counts"]
fmt = lambda n: f"{n:,}"
pct = lambda a, b: f"{fmt(a)}/{fmt(b)} ({100 * a / b:.1f}%)" if b else "0/0"

lines = [
    START,
    f"Generated by `scripts/update_readme_numbers.py` from `out/` (rules sha256 `{run['rules_sha256'][:8]}…`, as of {run['as_of']}).",
    "",
    "| Item | Value |",
    "|---|---|",
    f"| Buildings | {len(buildings)} ({', '.join(f'{v} {k}' for k, v in sorted(status.items(), key=lambda x: -x[1]))}) |",
    f"| Rules | {run['rule_count']} total, {run['rules_evaluated']} evaluated, {len(run.get('excluded', []))} excluded |",
    f"| Failed rules | {failed} |",
    f"| Verdicts on {run['as_of']} | " + " · ".join(f"{fmt(rc[k])} {k}" for k in sorted(rc, key=lambda k: -rc[k])) + " |",
    f"| Unknown verdicts | before {fmt(json.loads((ROOT / 'scripts/unknown_baseline.json').read_text())['unknown_before'])} "
    f"(baseline) -> now {fmt(rc.get('unknown', 0))} |",
    "",
    "| Test | Affected | Conflict flags | Notes |",
    "|---|---|---|---|",
]
for t in ["T1", "T2", "T3", "T4", "T5"]:
    c = changes[t]
    lines.append(f"| {t} | {len(c['affected_address_ids'])} | {len(c['conflict_flag_address_ids'])} | {c['notes'].replace('|', '/')} |")
voi_path = ROOT / "out/voi.json"
if voi_path.exists():
    voi = json.loads(voi_path.read_text())
    lines += ["", "**Value of information** (out/voi.json): the missing facts that would resolve the most unknown answers.", "",
              "| Missing fact | City | Unknown answers | Buildings | Rules |", "|---|---|---|---|---|"]
    for v in voi[:10]:
        lines.append(f"| {v['missing_fact']} | {v['city']} | {v['unknown_answers']} | {v['buildings']} | {len(v['rules'])} |")
lines.append(END)



ENV = {**os.environ, "ANTHROPIC_API_KEY": ""}
EXTRACTION_ENV = {**ENV, "PYTHONPATH": str(ROOT / "extraction/src")}
VERBATIM = """
import json
from extraction.selfcheck import OUT
from extraction.v3.loader import load
from extraction.v3.pipeline import _attach_deterministic_captures
from extraction.v3.verify import exact_or_normalized
docs = {d.doc_id: d for d in load()[0]}
_attach_deterministic_captures(docs)
rules = json.loads((OUT / "rules.json").read_text(encoding="utf-8"))["rules"]
exact = [r["team_rule_id"] for r in rules if r.get("source_doc_id") in docs
         and exact_or_normalized(docs[r["source_doc_id"]].raw, r.get("quoted_span"))[1] == "exact"]
print(json.dumps({"exact": len(exact), "total": len(rules)}))
"""


def python_with(*modules):
    probe = subprocess.run([sys.executable, "-c", "import " + ", ".join(modules)], capture_output=True)
    if probe.returncode == 0 or not shutil.which("uv"):
        return [sys.executable]
    return ["uv", "run", "--no-project", *[a for m in modules for a in ("--with", m)], "python"]


def sh(cmd, env=ENV):
    if not shutil.which(cmd[0]):
        return None, f"{cmd[0]} not found"
    p = subprocess.run(cmd, cwd=ROOT, env=env, capture_output=True, text=True)
    return p.returncode, p.stdout + p.stderr


def failed_text(code, out):
    last = (out.strip().splitlines() or [""])[-1][:120].replace("|", "/")
    return f"FAILED (exit {code}): {last}" if code is not None else f"not run: {out}"


def pytest_summary(code, out):
    counts = re.findall(r"(\d+) (passed|failed|errors?|skipped)", (out.strip().splitlines() or [""])[-1])
    text = ", ".join(f"{n} {w}" for n, w in counts)
    return text if code == 0 and text else failed_text(code, out)


py = python_with("pytest", "jsonschema")
commands = {
    "selfcheck": (py + ["-m", "extraction.selfcheck"], EXTRACTION_ENV),
    "verbatim": ([sys.executable, "-c", VERBATIM], EXTRACTION_ENV),
    "reproduce": ([sys.executable, "-m", "extraction.v3.reproduce"], EXTRACTION_ENV),
    "tests": (py + ["-m", "pytest", "-q", "engine/tests", "buildings/tests", "tests"], ENV),
    "extraction_tests": (["uv", "run", "--project", "extraction", "--with", "pytest", "python", "-m", "pytest",
                          "extraction/tests", "-q"], ENV),
}
with ThreadPoolExecutor(len(commands)) as pool:
    results = dict(zip(commands, pool.map(lambda c: sh(*c), commands.values())))

code, out = results["selfcheck"]
m = re.search(r"selfcheck: (\d+)/(\d+) pass", out)
selfcheck = (f"{m[1]}/{m[2]} pass" if code == 0 else f"FAILED: {m[1]}/{m[2]} pass") if m else failed_text(code, out)
code, out = results["verbatim"]
if code == 0:
    v = json.loads(out.strip().splitlines()[-1])
    verbatim = pct(v["exact"], v["total"])
else:
    verbatim = failed_text(code, out)
code, out = results["reproduce"]
reproduced = "yes" if code == 0 and "reproducible:" in out else f"no: {failed_text(code, out)}"

provided = {row["doc_id"] for row in csv.DictReader(open(ROOT / "starter pack/corpus/corpus_manifest.csv", newline=""))}
source_of = {r["team_rule_id"]: r.get("source_doc_id") for r in rules}
lookups = json.loads((ROOT / "out/lookups.json").read_text())
applies = [e for entries in lookups["lookups"].values() for e in entries if e["result"] == "applies"]
from_provided = sum(source_of.get(e["team_rule_id"]) in provided for e in applies)

check_lines = [
    CHECKS_START,
    f"Generated by `scripts/update_readme_numbers.py` (rules sha256 `{run['rules_sha256'][:8]}…`).",
    "",
    "| Check | Result |",
    "|---|---|",
    f"| Submission self-check (`python -m extraction.selfcheck`, report in `out/selfcheck_report.md`) | {selfcheck} |",
]
for t in ["T1", "T2", "T3", "T4", "T5"]:
    c = changes[t]
    check_lines.append(f"| {t}: affected addresses, addresses with a conflict flag (`out/changes.json`) | "
                       f"{len(c['affected_address_ids'])} affected, {len(c['conflict_flag_address_ids'])} flagged |")
check_lines += [
    "| Rules whose `quoted_span` is found verbatim: an exact substring of the raw text of the rule's `source_doc_id` "
    f"file (same test as the self-check) | {verbatim} |",
    f"| `applies` answers in `out/lookups.json` (as of {lookups['as_of']}) whose rule's `source_doc_id` is a document "
    f"of the provided corpus (`starter pack/corpus/corpus_manifest.csv`), not of `corpus_extra/` | "
    f"{pct(from_provided, len(applies))} |",
    f"| `out/rules.json` rebuilt byte for byte offline from the committed cache (`python -m extraction.v3.reproduce`) "
    f"| {reproduced} |",
    f"| Tests: `engine/tests`, `buildings/tests`, `tests` | {pytest_summary(*results['tests'])} |",
    f"| Tests: `extraction/tests` (uv project, model calls mocked) | {pytest_summary(*results['extraction_tests'])} |",
    f"| Rules in `out/rules.json` | {len(rules)} |",
    f"| Evidence-backed \"no rule\" findings (`no_rule_findings` in `out/rules.json`) | "
    f"{len(rules_file.get('no_rule_findings', []))} |",
    CHECKS_END,
]



sys.path.insert(0, str(ROOT))
from engine.coverage_v3 import _new_construction, backed_coverage
from engine.explain import SECONDARY_CONFIDENCE_CAP, is_secondary
from engine.prepare import is_ma_40p, source_types

as_of = date.fromisoformat(lookups["as_of"])
detail = json.loads((ROOT / "out/lookups_detail.json").read_text())["addresses"]
by_rule = defaultdict(Counter)
for entries in lookups["lookups"].values():
    for e in entries:
        by_rule[e["team_rule_id"]][e["result"]] += 1
findings = rules_file.get("no_rule_findings", [])
types = source_types()


def ids(rs):
    return f"{len(rs)}: " + ", ".join(r["team_rule_id"] for r in rs) if rs else "0"


def answers(rs):
    c = sum((by_rule[r["team_rule_id"]] for r in rs), Counter())
    return ", ".join(f"{fmt(n)} {k}" for k, n in c.most_common()) or "no lookup entry"


def effective_later(r):
    eff = r.get("effective_date")
    return r["status"] == "not_yet_effective" or (r["status"] == "in_force" and bool(eff) and eff > lookups["as_of"])


bars = [r for r in rules if is_ma_40p(r)]
no_rule_cells = {(f["jurisdiction"], f["category"]) for f in findings}
cap_in_no_rule_cell = sum(by_rule[r["team_rule_id"]]["applies"] for r in rules
                          if (r["jurisdiction"], r["category"]) in no_rule_cells)
only_in = [r for r in rules if r.get("applies_only_in")]
outside_city = sum(1 for a, entries in lookups["lookups"].items() for e in entries for r in only_in
                   if e["team_rule_id"] == r["team_rule_id"] and buildings[a]["legal_city"] != r["applies_only_in"])
secondary = [r for r in rules if is_secondary(r, types)]
secondary_answers = [x for a in detail.values() for rid, x in a["rules"].items()
                     if rid in {r["team_rule_id"] for r in secondary}]
capped = sum(x["confidence"] <= SECONDARY_CONFIDENCE_CAP and x["needs_review"] for x in secondary_answers)
with_unknown = [r for r in rules if by_rule[r["team_rule_id"]]["unknown"]]

withheld_lines = [
    "<a id='withheld-start'></a>",
    f"Generated by `scripts/update_readme_numbers.py` from `out/rules.json`, `out/lookups.json` and "
    f"`out/lookups_detail.json` (as of {lookups['as_of']}).",
    "",
    f"| Case | What the engine does | Rules | Answers on {lookups['as_of']} |",
    "|---|---|---|---|",
    "| Failed measure (`status: failed`) | Omitted from every lookup on every date (`engine/verdict.py`). | "
    f"{ids([r for r in rules if r['status'] == 'failed'])} | "
    f"{answers([r for r in rules if r['status'] == 'failed'])} |",
    "| Pending bill (`status: pending`) | Answered `pending`, never `applies`. | "
    f"{ids([r for r in rules if r['status'] == 'pending'])} | "
    f"{answers([r for r in rules if r['status'] == 'pending'])} |",
    "| Enacted, effective later | Answered `not_yet_effective` until its effective date. | "
    f"{ids([r for r in rules if effective_later(r)])} | {answers([r for r in rules if effective_later(r)])} |",
    "| Bar on local rent control (G.L. c. 40P): binds cities, not landlords | Never reported as a rent cap. It is listed "
    "at Massachusetts addresses as a statewide bar, and its conditions are read as limits on any permitted local "
    "regulation (`engine/verdict.py`). The cities it bars carry an evidence-backed \"no rule\" finding instead of a "
    "local cap; the self-check fails if an in-force rule sits in such a cell. | "
    f"{ids(bars)}; \"no rule\" findings: "
    + ", ".join(f"{f['jurisdiction']} ({f['category']})" for f in findings)
    + f" | the bar: {answers(bars)}; `applies` in a \"no rule\" cell: {cap_in_no_rule_cell} |",
    "| Event-only rule (`event_only: true`: plays only at an event such as a no-fault eviction, a demolition or a "
    "conversion) | Never wins a precedence edge, so it cannot supersede another rule (`engine/precedence.py`). Its "
    "building answer does not check whether the event occurred. | "
    f"{ids([r for r in rules if r.get('event_only')])} | {answers([r for r in rules if r.get('event_only')])} |",
    "| State law limited to one city (`applies_only_in`) | Evaluated as a rule of that city: omitted elsewhere in the "
    "state, `unknown` where the legal city rests on the postal city (`engine/verdict.py`). | "
    f"{ids(only_in)} | {answers(only_in)}; entries outside the named city: {outside_city} |",
    "| Secondary source (the source document is not `official` in the corpus manifests) | Confidence capped at "
    f"{SECONDARY_CONFIDENCE_CAP} and the answer sent to the review queue, even when the quote is exact "
    f"(`engine/explain.py`). | {ids(secondary)} | {answers(secondary)}; capped and sent to review: "
    f"{capped}/{len(secondary_answers)} |",
    "| A fact capable of changing coverage is missing | Answered `unknown`, naming the missing fact, never guessed. | "
    f"{len(with_unknown)} rules with at least one `unknown` answer | {fmt(rc.get('unknown', 0))} unknown |",
    "<a id='withheld-end'></a>",
]


def why_unknown(b, nc):
    if b.get("year_built") is None:
        return "year built missing"
    return "owner filing not in the data" if nc.get("requires_owner_filing") else "built in the cutoff year"


gaps_lines = [
    "<a id='gaps-start'></a>",
    f"Generated by `scripts/update_readme_numbers.py` from `out/rules.json`, `out/lookups_detail.json`, "
    f"`out/voi.json` and `out/buildings.json` (as of {lookups['as_of']}).",
    "",
    "**New-construction exemptions the building data cannot settle** (evidence-backed "
    "`coverage.new_construction_exemption`, tested with the engine's own function):",
    "",
    "| Rule | Jurisdiction | Exemption | Unknown answers | Why |",
    "|---|---|---|---|---|",
]
for r in rules:
    nc = backed_coverage(r).get("new_construction_exemption")
    if not isinstance(nc, dict):
        continue
    why = Counter(why_unknown(buildings[a], nc) for a, x in detail.items()
                  if x["rules"].get(r["team_rule_id"], {}).get("result") == "unknown"
                  and _new_construction(buildings[a], nc, as_of)[0] is None)
    if why:
        exemption = f"{nc.get('years')} years" + (", owner filing required" if nc.get("requires_owner_filing") else "")
        gaps_lines.append(f"| {r['team_rule_id']} | {r['jurisdiction']} | {exemption} | {sum(why.values())} | "
                          + ", ".join(f"{n} {k}" for k, n in why.most_common()) + " |")

voi_by_fact = defaultdict(lambda: {"answers": 0, "buildings": 0, "cities": set()})
for v in json.loads(voi_path.read_text()) if voi_path.exists() else []:
    f = voi_by_fact[v["missing_fact"]]
    f["answers"] += v["unknown_answers"]
    f["buildings"] += v["buildings"]
    f["cities"].add(v["city"])
gaps_lines += ["", "**Facts missing from the building data** (`out/voi.json`; one unknown answer can name several "
               "facts):", "", "| Missing fact | Unknown answers naming it | Buildings | Cities |", "|---|---|---|---|"]
for fact, f in sorted(voi_by_fact.items(), key=lambda x: -x[1]["answers"]):
    gaps_lines.append(f"| {fact} | {fmt(f['answers'])} | {f['buildings']} | {'; '.join(sorted(f['cities']))} |")

missing = Counter(m for b in buildings.values() for m in b.get("missing_facts", []))
fallback = [b for b in buildings.values() if b["city_status"] == "postal_fallback"]
fallback_unknown = sum("legal_city" in x["missing_facts"] for b in fallback
                       for x in detail[b["address_id"]]["rules"].values() if x["result"] == "unknown")
uncaptured = [r for r in rules if re.search(r"not captured", json.dumps([r.get("review_note"), r.get("source_notes")]),
                                            re.I)]
gaps_lines += [
    "",
    "- Facts named missing per building in `out/buildings.json`: "
    + ", ".join(f"`{m}` {n}/{len(buildings)}" for m, n in missing.most_common()) + ".",
    f"- Legal city taken from the postal city only (`city_status: postal_fallback`): "
    + (", ".join(f"{b['address_id']} ({b['legal_city']})" for b in fallback) or "none")
    + f"; city rules there are answered `unknown`: {fallback_unknown} answers.",
    f"- Rules whose own notes record that part of their source text was not captured: {ids(uncaptured)}.",
    "<a id='gaps-end'></a>",
]
nodash = lambda block: [s.replace("\u2014", "-").replace("\u2013", "-") for s in block]


def replace_block(path, start, end, block):
    text = path.read_text()
    i, j = text.index(start), text.index(end) + len(end)
    path.write_text(text[:i] + "\n".join(block) + text[j:])


readme = ROOT / "README.md"
replace_block(readme, START, END, lines)
replace_block(readme, CHECKS_START, CHECKS_END, nodash(check_lines))
for doc in (readme, ROOT / "engine/RESPONSIBLE_DESIGN.md"):
    replace_block(doc, "<a id='withheld-start'></a>", "<a id='withheld-end'></a>", nodash(withheld_lines))
    replace_block(doc, "<a id='gaps-start'></a>", "<a id='gaps-end'></a>", nodash(gaps_lines))
print("README numbers, checks, withheld answers and gaps updated (also in engine/RESPONSIBLE_DESIGN.md)")
